/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tarea02052020;

import java.net.*;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Brito Paredes
 */
public class Cliente extends javax.swing.JFrame {
    boolean activo=true;
    String direccionIP;
    int Puerto;
    Socket skCliente;
    String almacenarValorDigital;
    String cadena;
    String mensaje="";
    DataOutputStream out;
    InputStream aux;
    DataInputStream flujo;
    /**
     * Creates new form Cliente
     */
    public Cliente() {
        initComponents();
        jLabel4.setVisible(false);
        InValorDigital.setVisible(false);
        btnEnviarValor.setVisible(false);
        
    }
    public void conectar(String IP, int Puerto){
        try {
            skCliente = new Socket(IP, Puerto);
            out = new DataOutputStream(skCliente.getOutputStream());
            mensaje = " esta conectado";
            out.writeUTF("Cliente con IP "+skCliente.getInetAddress()+mensaje);
            areaText.append("El cliente "+ mensaje+ "\n");
            
            
            recibir r = new recibir() {};
            r.start();
                
            
        } catch (IOException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public abstract class recibir extends Thread{
        @Override
        public void run(){
            while(activo){
                try {
                    flujo = new DataInputStream(skCliente.getInputStream());
                    cadena = flujo.readUTF();
                    areaText.append(cadena+"\n");
                      
                } catch (IOException ex) {
                    Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        escribirIP = new javax.swing.JTextField();
        escribirPuerto = new javax.swing.JTextField();
        btnConectar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        InValorDigital = new javax.swing.JTextField();
        btnEnviarValor = new javax.swing.JButton();
        Estado = new javax.swing.JScrollPane();
        areaText = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cliente");

        jLabel2.setText("Ingresa la IP");

        jLabel3.setText("Ingresa el Puerto");

        btnConectar.setText("Conectar");
        btnConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarActionPerformed(evt);
            }
        });

        jLabel4.setText("Accion 0 o 1");

        btnEnviarValor.setText("Enviar");
        btnEnviarValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarValorActionPerformed(evt);
            }
        });

        areaText.setColumns(20);
        areaText.setRows(5);
        Estado.setViewportView(areaText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(escribirPuerto, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(escribirIP)
                            .addComponent(InValorDigital))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConectar)
                            .addComponent(btnEnviarValor))))
                .addContainerGap(140, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 177, Short.MAX_VALUE)
                .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(escribirIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(escribirPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnConectar)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(InValorDigital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviarValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarActionPerformed
        conectar(escribirIP.getText(), Integer.parseInt(escribirPuerto.getText()));
        jLabel4.setVisible(true);
        InValorDigital.setVisible(true);
        btnEnviarValor.setVisible(true);
        btnConectar.setEnabled(false);
        
    }//GEN-LAST:event_btnConectarActionPerformed

    private void btnEnviarValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarValorActionPerformed
            mensaje = InValorDigital.getText();
        try {
            
            skCliente = new Socket(escribirIP.getText(), Integer.parseInt(escribirPuerto.getText()));
            out = new DataOutputStream(skCliente.getOutputStream());
            out.writeUTF(mensaje);
            recibir recibido =new recibir() {};
            recibido.start();
            
            if(InValorDigital.getText().equals("F")){
                    JOptionPane.showMessageDialog(null,"Haz desconectado el cliente");
            }  
            
        } catch (IOException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }areaText.append("Enviado: "+ mensaje+ "\n");
        
    }//GEN-LAST:event_btnEnviarValorActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        new Cliente();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Estado;
    private javax.swing.JTextField InValorDigital;
    private javax.swing.JTextArea areaText;
    private javax.swing.JButton btnConectar;
    private javax.swing.JButton btnEnviarValor;
    private javax.swing.JTextField escribirIP;
    private javax.swing.JTextField escribirPuerto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
